// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalPortfolio.Data;

#nullable disable

namespace PersonalPortfolio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724195136_SeedSampleData")]
    partial class SeedSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PersonalPortfolio.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("PersonalPortfolio.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LiveUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A full-stack e-commerce solution with product catalog, shopping cart, and secure checkout powered by Stripe.",
                            ImageUrl = "https://placehold.co/600x400/1b6ec2/ffffff?text=E-Commerce",
                            LiveUrl = "https://example.com/ecommerce",
                            TechStack = "ASP.NET Core, Blazor, EF Core, SQL Server, Stripe",
                            Title = "E-Commerce Platform"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A collaborative task management application with real-time updates, drag-and-drop boards, and team workspaces.",
                            ImageUrl = "https://placehold.co/600x400/28a745/ffffff?text=Task+Manager",
                            LiveUrl = "https://example.com/tasks",
                            TechStack = "ASP.NET Core, SignalR, React, PostgreSQL",
                            Title = "Task Management App"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A responsive weather dashboard that displays current conditions, forecasts, and interactive maps using external APIs.",
                            ImageUrl = "https://placehold.co/600x400/dc3545/ffffff?text=Weather+App",
                            LiveUrl = "",
                            TechStack = "Blazor, Chart.js, OpenWeather API",
                            Title = "Weather Dashboard"
                        });
                });

            modelBuilder.Entity("PersonalPortfolio.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "AI",
                            IconClass = "fas fa-robot",
                            Name = "Agentic AI & RAG",
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            IconClass = "fas fa-server",
                            Name = "ASP.NET Core Backend Developer",
                            ProficiencyLevel = 5
                        },
                        new
                        {
                            Id = 3,
                            Category = "Frontend",
                            IconClass = "fas fa-code",
                            Name = "Frontend Developer",
                            ProficiencyLevel = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
